GCN:
<<<<<<< HEAD
  device_id: 2
  epochs: 200
  batch_size: 1024
  pooling_type: 'max'
  hid_dim: 128
=======
  device_id: 0
  epochs: 200
  batch_size: 128
  pooling_type: 'sum'
  hid_dim: 512
>>>>>>> 836cd2fd3e4bf95de625068f61a7abecafb5623e
  num_layer: 2
  num_parts: 100
  lr: 0.001
  weight_decay: 0.0001 

GIN:
<<<<<<< HEAD
  device_id: 1
=======
  device_id: 3
>>>>>>> 836cd2fd3e4bf95de625068f61a7abecafb5623e
  epochs: 100
  batch_size: 128
  pooling_type: 'sum'
  hid_dim: 128
  num_layer: 2
  num_parts: 100
  lr: 0.001
  weight_decay: 0.0001 