GCN:
  device_id: 0
  epochs: 200
  batch_size: 128
  pooling_type: 'sum'
  hid_dim: 512
  num_layer: 2
  num_parts: 100
  lr: 0.0001
  weight_decay: 0.0001 

GIN:
  device_id: 3
  epochs: 100
  batch_size: 256
  pooling_type: 'sum'
  hid_dim: 128
  num_layer: 2
  num_parts: 200
  lr: 0.001
  weight_decay: 0.0001 

