Cora:
  epochs: 100
  prompt_lr: 0.001
  prompt_weight_decay: 0.0005
  answering_lr: null
  answering_weight_decay: null

  trojan_outter_epochs: 100
  poison_ratio: 1
  trigger_size: 7
  target_class: 0

  hid_dim: 128
  trojan_pg_lr: 0.0001
  trojan_pg_weight_decay: 0.0001
  trigger_lr: 0.0001
  trigger_weight_decay: 0.0005

  trojan_dt_lr: null
  trojan_dt_weight_decay: null

Cora:
  epochs: 100
  prompt_lr: 0.001
  prompt_weight_decay: 0.0005
  answering_lr: null
  answering_weight_decay: null

  trojan_outter_epochs: 100
  poison_ratio: 1
  trigger_size: 7
  target_class: 0

  hid_dim: 128
  trojan_pg_lr: 0.0001
  trojan_pg_weight_decay: 0.0001
  trigger_lr: 0.0001
  trigger_weight_decay: 0.0005

  trojan_dt_lr: null
  trojan_dt_weight_decay: null
  