Cora:
  device_id: 3
  epochs: 100
  prompt_lr: 0.001
  prompt_weight_decay: 0.0005
  answering_lr: null
  answering_weight_decay: null
  dt_batch_size: 1024
  
  trojan_outter_epochs: 50
  poison_ratio: 0.1
  trigger_size: 7
  target_class: 0

  hid_dim: 128
  trojan_pg_lr: null
  trojan_pg_weight_decay: null
  trigger_lr: 0.0001
  trigger_weight_decay: 0.0005
  trojan_batch_size: 1024

  trojan_dt_lr: null
  trojan_dt_weight_decay: null

Citeseer:
  device_id: 3
  epochs: 100
  prompt_lr: 0.001
  prompt_weight_decay: 0.0005
  answering_lr: null
  answering_weight_decay: null
  dt_batch_size: 1024
  
  trojan_outter_epochs: 50
  poison_ratio: 0.01
  trigger_size: 7
  target_class: 1

  hid_dim: 128
  trojan_pg_lr: null
  trojan_pg_weight_decay: null
  trigger_lr: 0.0001
  trigger_weight_decay: 0.0005
  trojan_batch_size: 1024

  trojan_dt_lr: null
  trojan_dt_weight_decay: null

Pubmed:
  device_id: 3
  epochs: 100
  prompt_lr: 0.001
  prompt_weight_decay: 0.0005
  answering_lr: null
  answering_weight_decay: null
  dt_batch_size: 1024
  
  trojan_outter_epochs: 50
  poison_ratio: 0.1
  trigger_size: 7
  target_class: 0

  hid_dim: 512
  trojan_pg_lr: null
  trojan_pg_weight_decay: null
  trigger_lr: 0.0001
  trigger_weight_decay: 0.0005
  trojan_batch_size: 1024

  trojan_dt_lr: null
  trojan_dt_weight_decay: null